# Generated by Django 5.0.1 on 2024-03-05 21:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_quiz_close_datetime_alter_quiz_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="close_datetime",
            field=models.DateTimeField(default=base.models.default_close_datetime),
        ),
    ]
