# Generated by Django 5.0.1 on 2024-03-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_quiz_close_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
